config/routes.rb
Feeder::Application.routes.draw do
  get "proxy/proxy"

  resources :feed_aggregators

end

app/models/feed_aggregator.rb
class FeedAggregator < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/feed_aggregators_controller.rb
require 'feed-normalizer'
require 'open-uri'
require 'chronic'

class Integer
   def to_str
     self.to_s
   end
end


class FeedAggregatorsController < ApplicationController
  # GET /feed_aggregators
  # GET /feed_aggregators.json
  def index
    @feed_aggregators = FeedAggregator.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @feed_aggregators }
    end
  end

  # GET /feed_aggregators/1
  # GET /feed_aggregators/1.json
  def show
    @feed_aggregator = FeedAggregator.find(params[:id])


feeds = @feed_aggregator.feeds.split("\n")
totalout = ''
loop = 1
feeds.each do |feedurl|
uri = URI.parse(feedurl.strip)
inituri = feedurl
	if uri.scheme == "https"
	#If this doesn't work, Comment out this line, and uncomment the one below it.
	feedurl = "http://dakamotech.net/https.php?url=" + feedurl
	#feedurl = "http://localhost:3000/proxy/proxy?url=" + feedurl
	end
puts "Getting Feed " + loop + " Of " + feeds.length + "..."
feed = FeedNormalizer::FeedNormalizer.parse open(feedurl.strip)
feed.clean!
puts "Feed " + loop + " - " + feed.title.sub("Posts of ", "")
title = '<span style="font-size:16px;">' + feed.title.sub("Posts of ", "") + '</span><br />'
totalout = totalout + title + feed.entries.first.content + "<hr />"
date = nil
tryone = Date.parse(feed.entries.first.title)
if !tryone
trytwo = Chronic.parse(feed.entries.first.title)
date = Date.parse trytwo
else
date = tryone
end
datenow = Date.parse Time.now.strftime("%Y-%m-%d")
if datenow == date
else
puts "TBA - Ahead Posts"
end
loop += 1
end
$feedhtml = totalout





    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @feed_aggregator }
      format.pdf { 
      kit = PDFKit.new($feedhtml, :page_size => 'Letter')
      output = kit.to_pdf
      render :text => output}
    end
  end

  # GET /feed_aggregators/new
  # GET /feed_aggregators/new.json
  def new
    @feed_aggregator = FeedAggregator.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @feed_aggregator }
    end
  end

  # GET /feed_aggregators/1/edit
  def edit
    @feed_aggregator = FeedAggregator.find(params[:id])
  end

  # POST /feed_aggregators
  # POST /feed_aggregators.json
  def create
    @feed_aggregator = FeedAggregator.new(params[:feed_aggregator])

    respond_to do |format|
      if @feed_aggregator.save
        format.html { redirect_to @feed_aggregator, :notice => 'Feed aggregator was successfully created.' }
        format.json { render :json => @feed_aggregator, :status => :created, :location => @feed_aggregator }
      else
        format.html { render :action => "new" }
        format.json { render :json => @feed_aggregator.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /feed_aggregators/1
  # PUT /feed_aggregators/1.json
  def update
    @feed_aggregator = FeedAggregator.find(params[:id])

    respond_to do |format|
      if @feed_aggregator.update_attributes(params[:feed_aggregator])
        format.html { redirect_to @feed_aggregator, :notice => 'Feed aggregator was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @feed_aggregator.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /feed_aggregators/1
  # DELETE /feed_aggregators/1.json
  def destroy
    @feed_aggregator = FeedAggregator.find(params[:id])
    @feed_aggregator.destroy

    respond_to do |format|
      format.html { redirect_to feed_aggregators_url }
      format.json { head :ok }
    end
  end
end

app/controllers/proxy_controller.rb
require 'uri'
require 'net/http'
class ProxyController < ApplicationController
  def proxy
  render :layout => false
  url = params[:url] 
  $out = Net::HTTP.get_response(URI.parse(url)).body
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feed_aggregators_helper.rb
module FeedAggregatorsHelper
end

app/helpers/proxy_helper.rb
module ProxyHelper
end

app/views/feed_aggregators/_form.html.erb
<%= form_for(@feed_aggregator) do |f| %>
  <% if @feed_aggregator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed_aggregator.errors.count, "error") %> prohibited this feed_aggregator from being saved:</h2>

      <ul>
      <% @feed_aggregator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :feeds %><br />
    <%= f.text_area(:feeds, "cols" => 130, "rows" => 8)%>
    <br />
    One Per Line
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feed_aggregators/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed_aggregator %> |
<%= link_to 'Back', feed_aggregators_path %>

app/views/feed_aggregators/index.html.erb
<h1>Listing Feed Aggregators</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Desc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feed_aggregators.each do |feed_aggregator| %>
  <tr>
    <td><%= feed_aggregator.title %></td>
    <td><%= feed_aggregator.desc %></td>
    <td><%= link_to 'Show', feed_aggregator %></td>
    <td><%= link_to 'Edit', edit_feed_aggregator_path(feed_aggregator) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feed aggregator', new_feed_aggregator_path %>

app/views/feed_aggregators/new.html.erb
<h1>New feed_aggregator</h1>

<%= render 'form' %>

<%= link_to 'Back', feed_aggregators_path %>

app/views/feed_aggregators/show.html.erb
<p id="notice"><%= notice %></p>


<div style="padding-left:15px">
<span style="font-size:22px"><%=@feed_aggregator.title%></span>
<br />
<%=raw $feedhtml %>
</div>

<p>
  <b>Description:</b>
  <%= @feed_aggregator.desc %>
</p>

<p>
  <b>Feeds:</b>
  <ul>
  <%
  feeds = @feed_aggregator.feeds.split("\n")
  feeds.each do |feedurl|
  %>
  <li><%=feedurl%></li>
  <%end%>
  </ul>
</p>









<%= link_to 'Edit', edit_feed_aggregator_path(@feed_aggregator) %> |
<%= link_to 'Back', feed_aggregators_path %> | 
<a href="<%=request.url%>.pdf">PDF</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Feeder</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/proxy/proxy.html.erb
<%=raw $out %>